### ISSUE TITLE
Version mismatches between GitHub and BioConductor

### ISSUE THREAD

**Issue by esimonds** [JinmiaoChenLab/cytofkit#5]
I really appreciate how you guys keep updating Cytofkit, but it would be nice if the default BioConductor command and/or the devtools::install_github("haoeric/cytofkit_devel") command (as recommended on the first page of this GitHub) always installed the latest version. Currently it's pretty random which version I get based on how I install it. 

For example:

**Bioconductor is hosting version 1.8.1, but only if you download it manually:**
https://bioconductor.org/packages/release/bioc/html/cytofkit.html
```
DESCRIPTION:
Package: cytofkit
Type: Package
Title: cytofkit: an integrated mass cytometry data analysis pipeline
Version: 1.8.1
Date: 2017-04-26
```

I was able to download the package from Github at 
https://bioconductor.org/packages/release/bioc/src/contrib/cytofkit_1.8.1.tar.gz
and install it from source. This seems to be the only way to get the latest version.

**Installing via biocLite gives me a different version, 1.6.5:**
```
> biocLite("cytofkit")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.4 (BiocInstaller 1.24.0), R 3.3.3 (2017-03-06).
Installing package(s) ‘cytofkit’
trying URL 'https://bioconductor.org/packages/3.4/bioc/bin/macosx/mavericks/contrib/3.3/cytofkit_1.6.5.tgz'
Content type 'application/x-gzip' length 5007107 bytes (4.8 MB)
==================================================
downloaded 4.8 MB
```

**And the latest version on the GitHub devel branch as of right now (May 22, 2017) is 1.7.1:**
```
> devtools::install_github("haoeric/cytofkit_devel")
# omitted a bunch of installation messages
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.4

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] cytofkit_1.7.1  
```

Maybe it's something weird about my configuration, but I've tried on two systems now (both R 3.3.3 on OS X Sierra) and had the same issue. If there's a better way to install, please educate me. Thanks!

**Comment by jinmiaochen** [comment]
Dear Erin,

We will look into this issue and rectify it as soon as we can. Thanks a lot for your feedback.

Best,
Jinmiao

**Comment by MattMyint** [comment]
Hi Erin,

cytofkit v1.6.5 was the release for Bioconductor v3.4, whereas the version listed on the package's Bioconductor page (cytofkit v1.8.1) was the release for Bioconductor v3.5.

Our latest devel branch is `v1.9.1`, and is hosted [here](https://github.com/JinmiaoChenLab/cytofkit). Using devtools:
`devtools::install_github("/JinmiaoChenLab/cytofkit")`

You may wish to try our devel branch to test any new features as we implement them by installing from our GitHub.
Otherwise if you need a stable version, installing via BiocLite will be good enough. Just take note that BiocLite will install the release version of cytofkit that matches the version of Bioconductor on your machine

> Bioconductor v3.3 - cytofkit v1.4.z
> Bioconductor v3.4 - cytofkit v1.6.z
> Bioconductor v3.5 - cytofkit v1.8.z

Hope this helps!

Matthew

**Comment by MattMyint** [comment]
If there's anything else that needs clarification, feel free to reopen the issue!

Thanks
Matthew
