### ISSUE TITLE
Unable to download cytofkit 

### ISSUE THREAD

**Issue by rubikslucio** [JinmiaoChenLab/cytofkit#55]
Hi Guys, I am trying to install cytofkit in my windows 7. I inputed the command BiocManager::install("JinmiaoChenLab/cytofkit") but its not downloading the cytofkit package. Please help. Thanks. 
Here is the output code. 
> BiocManager::install("JinmiaoChenLab/cytofkit")
Bioconductor version 3.8 (BiocManager 1.30.4), R 3.5.1 (2018-07-02)
Installing github package(s) 'JinmiaoChenLab/cytofkit'
Downloading GitHub repo JinmiaoChenLab/cytofkit@master
   checking for file 'C:\Users\ExpMedUser\AppData\Local\Temp\RtmpmUliSo\remotes171c3553484c\JinmiaoChenLab-cytofkit-c4f93e5/DESCRIPTION' ...
   checking for file 'C:\Users\ExpMedUser\AppData\Local\Temp\RtmpmUliSo\remotes171c3553484c\JinmiaoChenLab-cytofkit-c4f93e5/DESCRIPTION' ... 
√  checking for file 'C:\Users\ExpMedUser\AppData\Local\Temp\RtmpmUliSo\remotes171c3553484c\JinmiaoChenLab-cytofkit-c4f93e5/DESCRIPTION' (1.3s)
-  preparing 'cytofkit':
   checking DESCRIPTION meta-information ...
   checking DESCRIPTION meta-information ... 
√  checking DESCRIPTION meta-information
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'cytofkit_1.11.3.tar.gz'
* installing *source* package 'cytofkit' ...
** libs
*** arch - i386
C:/Program Files/Rtools/mingw_32/bin/g++  -I"E:/R-3.5.1/include" -DNDEBUG  -I"E:/R-3.5.1/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/Program: not found
make: *** [RcppExports.o] Error 127
ERROR: compilation failed for package 'cytofkit'
* removing 'E:/R-3.5.1/library/cytofkit'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/EXPMED~1/AppData/Local/Temp/RtmpmUliSo/file171c4ed26d50/cytofkit_1.11.3.tar.gz’ had non-zero exit status
In addition: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers

Thanks.

**Comment by SamGG** [comment]
Hi,
RTools is not installed at the default location. Install it at the root of the disk C:\, and the installation will finish. The current error is in fact **C:/Program: not found**. Because RTools is currently  in the "C:/Program Files", the full command line "C:/Program Files/Rtools/mingw_32/bin/g++" has been split at the first space separator. So please install it at the root of your disk.
HTH

**Comment by rubikslucio** [comment]
Hi SamGG,

Thank you for the help. I tried downloading Rtools using the command BiocManager::install("Rtools") this is the output.
> BiocManager::install("Rtools")
Bioconductor version 3.8 (BiocManager 1.30.4), R 3.5.1 (2018-07-02)
Installing package(s) 'Rtools'
Update old packages: 'processx'
Update all/some/none? [a/s/n]: a
  There is a binary version available but the source version is later:
         binary source needs_compilation
processx  3.2.0  3.2.1              TRUE
  Binaries will be installed
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.5/processx_3.2.0.zip'
Content type 'application/zip' length 300367 bytes (293 KB)
downloaded 293 KB
package ‘processx’ successfully unpacked and MD5 sums checked
The downloaded binary packages are in
        C:\Users\ExpMedUser\AppData\Local\Temp\RtmpeiMqCR\downloaded_packages
Warning message:
package ‘Rtools’ is not available (for R version 3.5.1) 

 Is there a different way to save the Rtools in my C drive then the one I am trying? Thanks for the help.

**Comment by SamGG** [comment]
Hi.
Rtools is not a package of R. Rtools is a program. It must be install apart from R or RStudio. It brings tools to R, tools to build packages. You will find Rtools at . Since Rtools is already installed in your computer, I thought you did it. Please uninstall the current Rtools from your computer, restart your computer, then install Rtools as administrator, using default proposals but adding Rtools to the PATH variable. I did it on many computers of trainees and this procedure works.
Best

**Comment by rubikslucio** [comment]
Hi SamGG,

Thank you so much for the help it worked.
Best
