### ISSUE TITLE
parameter of cytofAsinh

### ISSUE THREAD

**Issue by hujingchu** [JinmiaoChenLab/cytofkit#75]
Hi,
How can I change the parameter cofactor to 150 of cytofAsinh while using cytof_exprsMerge?

**Comment by SamGG** [comment]
Hi,
Currently I would say that is not possible. I could fix it easily if you need it. More on that below.

Nevertheless, may I ask you why you wish to set a cofactor so high with cytof data? Or, if your data come from fluorescent cytometry, why you wish to use cytofAsinh as a transformation?

Best.

To fix quickly.
Change line 124 to
`a_a = 1, a_b = 1, a_c =0, cofactor = 5) { `
instead of
https://github.com/JinmiaoChenLab/cytofkit/blob/c4f93e5d849cf670c3825e5abacd850822c8eca7/R/cytof_preProcess.R#L124
Change the end of line 171 to
`2, cytofAsinh, cofactor)`
instead of 
https://github.com/JinmiaoChenLab/cytofkit/blob/c4f93e5d849cf670c3825e5abacd850822c8eca7/R/cytof_preProcess.R#L124
Finally, add `cofactor = 150` in your call to `cytof_exprsMerge`. This should do the job passing the cofactor up to the `cytofAsinh `function.


The current function calls are the followings.

There is a cofator argument in cytofAsinh, and you should set it `cofactor = 150`. `cytof_exprsMerge` function allows some extra arguments `...` to be passed to the transformation method. But in between, there is a cal to `cytof_exprsExtract ` that looses all the flexibility of the `...` argument. You had probably investigated this.
https://github.com/JinmiaoChenLab/cytofkit/blob/c4f93e5d849cf670c3825e5abacd850822c8eca7/R/cytof_preProcess.R#L27-L33
https://github.com/JinmiaoChenLab/cytofkit/blob/c4f93e5d849cf670c3825e5abacd850822c8eca7/R/cytof_preProcess.R#L38-L42
https://github.com/JinmiaoChenLab/cytofkit/blob/c4f93e5d849cf670c3825e5abacd850822c8eca7/R/cytof_preProcess.R#L117-L124
https://github.com/JinmiaoChenLab/cytofkit/blob/c4f93e5d849cf670c3825e5abacd850822c8eca7/R/cytof_preProcess.R#L250

**Comment by hujingchu** [comment]
Hi,
Thanks, yes, the data was from flow cytometry, I am a new beginner of analysising fsc data, I really dont know what's the difference between cytofAsinh and arcsinh from flowCore.
According to the code, except for the negative values,  the cytofAsinh is just a transform of arcsinh, the cofactor is similar to the a_b, and a_a and a_c are set to 1 and 0 specifically, but I cant tell why
Is there any materials I can learn from?
Thanks again~
Best

**Comment by SamGG** [comment]
You got it. The main point is that mass cytometry are positive whereas flow could be negative due to the noise and the compensation processing. This is the reason I would not process flow data with the cytofAsinh. The definition of the transformation in flowCore is `asinh(a+b*x)+c`. There is no reason to shift the data before or after the transformation, so both a and c should be zero. The remaining parameter is b which is equal to `1/cofactor`.
I think you should read https://f1000research.com/articles/6-748 and http://cytof.biosurf.org/#!/cytof. FlowSOM and tSNE are also a must read those days.
Best

**Comment by hujingchu** [comment]
Thank you so much
Best
